### PR TITLE
Support for systemd. Update xrdp.spec.in

### PR DESCRIPTION
**Pull request by illaxaer**
Added
%{_unitdir}/*
for support systemd

### CODE REVIEW

**Comment by metalefty** [comment]
Already fixed in develop branch, but thanks. I will merge develop into master shortly.

**Comment by metalefty** [comment]
@illaxaer I made additional fixes for packing list. Please try develop branch and close this issue if it works for you. Then I will merge develop into master.

**Comment by illaxaer** [comment]
I tried develop branch. It works good, without any error.
Distr: Fedora 21/
Used  options: --branch devel --noinstall and --branch devel --noinstall --nox11rdp --with-xorg-driver.

**Comment by metalefty** [comment]
Merged into master. Thanks for testing.

**Pull request closed without merging**
